import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PdfPreviewScreen extends StatefulWidget {
  final Map<String, dynamic> reportData;

  const PdfPreviewScreen({Key? key, required this.reportData}) : super(key: key);

  @override
  State<PdfPreviewScreen> createState() => _PdfPreviewScreenState();
}

class _PdfPreviewScreenState extends State<PdfPreviewScreen> {
  bool _isLoading = false;
  String? _errorMessage;
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    _generatePdf();
  }

  Future<void> _generatePdf() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final pdf = pw.Document();

      final logo = await imageFromAssetBundle('assets/images/app_logo.png');
      final cropImagePath = widget.reportData['cropImagePath'] as String?;
      pw.ImageProvider? cropImage;
      if (cropImagePath != null && File(cropImagePath).existsSync()) {
        cropImage = pw.MemoryImage(File(cropImagePath).readAsBytesSync());
      }

      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            margin: const pw.EdgeInsets.all(24),
            theme: pw.ThemeData.withFont(
              base: await PdfGoogleFonts.robotoRegular(),
              bold: await PdfGoogleFonts.robotoBold(),
            ),
          ),
          build: (context) => [
            _buildHeader(logo),
            pw.SizedBox(height: 16),
            _buildAnalysisSection(widget.reportData),
            pw.SizedBox(height: 16),
            _buildCropInfo(widget.reportData),
            pw.SizedBox(height: 16),
            _buildHealthScore(widget.reportData),
            pw.SizedBox(height: 16),
            _buildDiseaseDetection(widget.reportData),
            pw.SizedBox(height: 16),
            _buildRecommendations(widget.reportData),
            pw.SizedBox(height: 16),
            if (cropImage != null) _buildImageSection(cropImage),
            pw.SizedBox(height: 24),
            _buildFooter(),
          ],
        ),
      );

      final bytes = await pdf.save();
      setState(() {
        _pdfBytes = bytes;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = 'Error generating PDF: $e';
        _isLoading = false;
      });
    }
  }

  pw.Widget _buildHeader(pw.ImageProvider logo) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Row(
          children: [
            pw.Image(logo, width: 50, height: 50),
            pw.SizedBox(width: 12),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Crop Analyzer Report',
                    style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text('Generated by Crop Analyzer App',
                    style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              ],
            ),
          ],
        ),
        pw.Text(
          'Date: ${DateTime.now().toLocal().toString().split(' ')[0]}',
          style: pw.TextStyle(fontSize: 12),
        ),
      ],
    );
  }

  pw.Widget _buildAnalysisSection(Map<String, dynamic> data) {
    return pw.Container(
      decoration: pw.BoxDecoration(
        color: PdfColors.green100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Analysis Details',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Text('Report ID: ${data['reportId'] ?? 'N/A'}'),
          pw.Text('Date: ${data['date'] ?? 'N/A'}'),
          pw.Text('Location: ${data['location'] ?? 'Unknown'}'),
        ],
      ),
    );
  }

  pw.Widget _buildCropInfo(Map<String, dynamic> data) {
    return pw.Container(
      decoration: pw.BoxDecoration(
        color: PdfColors.blue100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Crop Information',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              _buildTableRow('Crop Type', data['cropType'] ?? 'N/A'),
              _buildTableRow('Variety', data['variety'] ?? 'N/A'),
              _buildTableRow('Growth Stage', data['growthStage'] ?? 'N/A'),
            ],
          ),
        ],
      ),
    );
  }

  pw.TableRow _buildTableRow(String label, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(value),
        ),
      ],
    );
  }

  pw.Widget _buildHealthScore(Map<String, dynamic> data) {
    final score = (data['healthScore'] ?? 0).toDouble();
    final color = score >= 80
        ? PdfColors.green
        : score >= 50
        ? PdfColors.orange
        : PdfColors.red;

    return pw.Container(
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Health Score',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Row(
            children: [
              pw.Container(
                width: 100,
                height: 10,
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey300,
                  borderRadius: pw.BorderRadius.circular(5),
                ),
                child: pw.Container(
                  width: score,
                  height: 10,
                  decoration: pw.BoxDecoration(
                    color: color,
                    borderRadius: pw.BorderRadius.circular(5),
                  ),
                ),
              ),
              pw.SizedBox(width: 8),
              pw.Text('$score%', style: pw.TextStyle(color: color)),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildDiseaseDetection(Map<String, dynamic> data) {
    final detections = data['detections'] as List<dynamic>? ?? [];
    return pw.Container(
      decoration: pw.BoxDecoration(
        color: PdfColors.red100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Disease / Pest Detection',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          if (detections.isEmpty)
            pw.Text('No diseases or pests detected.')
          else
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text('Name', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text('Confidence', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    ),
                  ],
                ),
                ...detections.map((d) {
                  return pw.TableRow(
                    children: [
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text(d['name'] ?? 'Unknown'),
                      ),
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text('${d['confidence'] ?? 0}%'),
                      ),
                    ],
                  );
                }),
              ],
            ),
        ],
      ),
    );
  }

  pw.Widget _buildRecommendations(Map<String, dynamic> data) {
    final recommendations = data['recommendations'] as List<dynamic>? ?? [];
    return pw.Container(
      decoration: pw.BoxDecoration(
        color: PdfColors.amber100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      padding: const pw.EdgeInsets.all(12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Recommendations',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          if (recommendations.isEmpty)
            pw.Text('No specific recommendations available.')
          else
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: recommendations
                  .map((r) => pw.Bullet(text: r.toString()))
                  .toList(),
            ),
        ],
      ),
    );
  }

  pw.Widget _buildImageSection(pw.ImageProvider cropImage) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Crop Image',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.Center(
          child: pw.Image(cropImage, width: 300, height: 200, fit: pw.BoxFit.cover),
        ),
      ],
    );
  }

  pw.Widget _buildFooter() {
    return pw.Column(
      children: [
        pw.Divider(),
        pw.SizedBox(height: 8),
        pw.Text('Crop Analyzer © ${DateTime.now().year}',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        pw.Text('Empowering farmers with AI-driven insights',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      ],
    );
  }

  Future<void> _savePdf() async {
    if (_pdfBytes == null) return;
    try {
      final dir = await getApplicationDocumentsDirectory();
      final file = File('${dir.path}/crop_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
      await file.writeAsBytes(_pdfBytes!);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('PDF saved to ${file.path}')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error saving PDF: $e')),
      );
    }
  }

  Future<void> _sharePdf() async {
    if (_pdfBytes == null) return;
    try {
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/crop_report.pdf');
      await file.writeAsBytes(_pdfBytes!);
      await Share.shareXFiles([XFile(file.path)], text: 'Crop Analyzer Report');
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error sharing PDF: $e')),
      );
    }
  }

  Future<void> _printPdf() async {
    if (_pdfBytes == null) return;
    try {
      await Printing.layoutPdf(onLayout: (_) async => _pdfBytes!);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error printing PDF: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PDF Preview'),
        actions: [
          IconButton(icon: const Icon(Icons.print), onPressed: _printPdf),
          IconButton(icon: const Icon(Icons.share), onPressed: _sharePdf),
          IconButton(icon: const Icon(Icons.download), onPressed: _savePdf),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _errorMessage != null
          ? Center(child: Text(_errorMessage!, style: const TextStyle(color: Colors.red)))
          : _pdfBytes == null
          ? const Center(child: Text('No PDF available'))
          : PdfPreview(
        build: (format) async => _pdfBytes!,
        allowPrinting: true,
        allowSharing: true,
        canChangeOrientation: false,
        canChangePageFormat: false,
        pdfFileName: 'crop_report.pdf',
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _generatePdf,
        icon: const Icon(Icons.refresh),
        label: const Text('Regenerate'),
      ),
    );
  }
}